name: Build and Run .NET Core App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Replace API Key in Config File
        run: |
          # Replace {API_KEY} in appsettings.json with the secret value
          sed -i 's|"{API_KEY}"|'"${{ secrets.YOUR_SECRET_NAME }}"'|g' Telegram.Bot.AsJoke.Polling/appsettings.json
        env:
          YOUR_SECRET_NAME: ${{ secrets.YOUR_SECRET_NAME }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore 
      
    - name: Run .NET Core App
      run: dotnet run -configuration Release --project Telegram.Bot.AsJoke.Polling/Telegram.BotAsJoke.Polling.csproj
