name: Docker Image Build and Deploy - devbotvm

on:
  push:
    branches:
      - dev
      - main

jobs:
  - name: Deploy to dev environment
    if: github.ref == 'refs/heads/dev'
    uses: ./docker-image-dev.yml

  - name: Deploy to main environment
    if: github.ref == 'refs/heads/main'
    uses: ./docker-image-main.yml
