name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t dbabych/devbotvm:latest .
        docker push dbabych/devbotvm:latest

    - name: SSH into Target Environment and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TARGET_HOST }}
        username: ${{ secrets.TARGET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export API_KEY=${{ secrets.API_KEY }}
          export APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
          printenv  # Print environment variables for debugging
          docker pull dbabych/devbotvm:latest
          docker stop devbotvm || true
          docker rm devbotvm || true
          docker run -d \
          -e API_KEY=$API_KEY \
          -e APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_INSTRUMENTATIONKEY \
          --name devbotvm --restart always dbabych/devbotvm:latest