jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        run: |
          docker build -t dbabych/testbotvm:latest .
          docker push dbabych/testbotvm:latest
    
  deployment-dev:
    needs: build
    runs-on: ubuntu-latest
      - name: SSH into Target Environment and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export API_KEY=${{ secrets.API_KEY }}
            export SESSION_STORAGE_CS=${{ secrets.SESSION_STORAGE_CS }}
            export APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
            docker pull dbabych/testbotvm:latest
            docker stop testbotvm || true
            docker rm testbotvm || true
            docker run -d \
            -e API_KEY=$API_KEY \
            -e SESSION_STORAGE_CS=$SESSION_STORAGE_CS \
            -e APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_INSTRUMENTATIONKEY \
            --name testbotvm --restart always dbabych/testbotvm:latest
