name: Build and Run .NET Core App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1  # You can change this to the version you need

    - name: Build .NET Core App
      run: dotnet build -c Release

    - name: Run .NET Core App
      run: dotnet run -c Release --project Telegram.Bot.AsJoke/Telegram.Bot.AsJoke.Polling/Telegram.BotAsJoke.Polling.csproj
