name: Start Docker Containers

on:
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  start-container-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Deploy only if the branch is main
    steps:
      - name: Start Docker Containers on Remote Server - main
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # start the specific Docker image
            docker start $(docker ps -q --filter ancestor=dbabych/devbotvm:latest) || true

  start-container-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  # Deploy only if the branch is dev
    steps:
      - name: Start Docker Containers on Remote Server - test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # start the specific Docker image
            docker start $(docker ps -q --filter ancestor=dbabych/testbotvm:latest) || true
